### ISSUE TITLE
Renaming DLL's from local repository

### ISSUE THREAD

**Issue by Dr-Irv** [fmarot/nativedependencies-maven#29]
I posted this question to StackOverflow:  https://stackoverflow.com/questions/50421441/using-maven-with-dll-from-third-party-and-managing-the-name-of-the-dll

I couldn't tag it with `nativedependencies-maven` because the tag would be new, and I don't have the reputation.

Looking forward to your answer.

**Comment by fmarot** [comment]
Looks like I can't create this tag too ! I'll remove the suggestion from the README. I suggested a solution on stackoverflow, let me know the result.

**Comment by Dr-Irv** [comment]
Yes, that helped.  I posted a new answer on stackoverflow that detailed what I did to get it working.  The trick was to package the DLL in a jar.
